export const sampleMessages = [
  {
    id: 1,
    sender: "Sarah",
    content: "Hey! Are we still meeting for coffee tomorrow?",
    time: "10:15 AM",
    isUser: false,
  },
  {
    id: 2,
    sender: "You",
    content: "Absolutely! How about 2pm at the usual spot?",
    time: "10:17 AM",
    isUser: true,
  },
  {
    id: 3,
    sender: "Sarah",
    content: "Perfect! Looking forward to catching up.",
    time: "10:18 AM",
    isUser: false,
  },
  {
    id: 4,
    sender: "Sarah",
    content: "I've got so much to tell you about my new project!",
    time: "10:19 AM",
    isUser: false,
  },
];

export const sampleChats = [
  {
    id: "1",
    name: "Sarah Johnson",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Can't wait to see you tomorrow!",
    time: "10:32 AM",
    unread: 3,
    isOnline: true,
    isPinned: true,
  },
  {
    id: "2",
    name: "Work Team",
    avatar: "/api/placeholder/40/40",
    lastMessage: "John: I've updated the presentation slides",
    time: "9:15 AM",
    unread: 1,
    isOnline: false,
    isPinned: true,
  },
  {
    id: "3",
    name: "David Chen",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Thanks for your help with the project",
    time: "Yesterday",
    unread: 0,
    isOnline: true,
    isPinned: false,
  },
  {
    id: "4",
    name: "Emma Wilson",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Did you see the latest episode?",
    time: "Yesterday",
    unread: 0,
    isOnline: false,
    isPinned: false,
  },
  {
    id: "5",
    name: "Family Group",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Mom: We're planning a barbecue this weekend",
    time: "Monday",
    unread: 0,
    isOnline: false,
    isPinned: false,
  },
  {
    id: "6",
    name: "Alex Rivera",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Let's meet up for coffee sometime",
    time: "Monday",
    unread: 0,
    isOnline: true,
    isPinned: false,
  },
  {
    id: "7",
    name: "Tech Support",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Your ticket #45872 has been resolved",
    time: "Sep 15",
    unread: 0,
    isOnline: false,
    isPinned: false,
  },
  {
    id: "8",
    name: "Sophia Lee",
    avatar: "/api/placeholder/40/40",
    lastMessage: "The documents are ready for review",
    time: "Sep 14",
    unread: 0,
    isOnline: true,
    isPinned: false,
  },
  {
    id: "9",
    name: "Book Club",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Next meeting: October 3rd at 7pm",
    time: "Sep 10",
    unread: 0,
    isOnline: false,
    isPinned: false,
  },
  {
    id: "10",
    name: "James Peterson",
    avatar: "/api/placeholder/40/40",
    lastMessage: "Hope to catch up soon!",
    time: "Aug 29",
    unread: 0,
    isOnline: false,
    isPinned: false,
  },
];
